defconfig: fix f2fs mount issues / fstrim
error: Operation not supported on transport endpoint

fixes: https://github.com/Suicide-Squirrel/issues_oreo/issues/4

(cherry picked from commit df8960adcf459b098cefb86a293dc53ed91af2c7)